spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.17:9092
          zk-nodes: 192.168.1.17:2181
          auto-create-topics: true

      bindings:
        elk:
          destination: elk
          contentType: application/json
      default-binder: kafka